export enum ENUM_PRODUCT_FILTER_LIST {
  ALL = 'Shop All',
  SHIRTS = 'Shirts',
  SHORTS = 'Shorts',
  SUIT = 'Suit',
  SHOES = 'Shoes',
  COAT = 'Coat',
  PANTS = 'Pants',
  BAGS = 'Bags',
  TSHIRTS = 'T-shirts',
  HOODIES = 'Hoodies',
  ACCESSORIES = 'Accessories',
  HAT = 'Hat',
  JACKET = 'Jacket',
}
