export type ProductType = {
  img: string;
  product_name: string;
  price: string;
};

export type ProductFormDataType = {
  name: string;
  price: string;
  description: string;
  weight: number | null;
  images: string[];
  sizes: string[];
  colors: string[];
  category: string;
};

export type ProductDetailType = {
  id: string;
  created_at: string;
  name: string;
  price: string;
  description: string;
  images: string[];
  sizes: string[];
  colors: string[];
  sold_out: boolean;
  weight: number;
  category: string;
  frequently_bought?: boolean;
  pre_order?: boolean;
};

export type ShoppingBagType = {
  id: string;
  created_at: string;
  name: string;
  price: string;
  image: string;
  color: string;
  size: string;
  weight: number;
  user_email: string;
  user_id: string;
};

export type DeliveryDetailsType = {
  id?: string;
  detail_id?: string;
  created_at?: string;
  user_email: string;
  first_name: string;
  last_name: string;
  country: string;
  city: string;
  address: string;
  zip_code: string;
  phone_number: string;
};

export type PlacedOrderDetailsType = {
  first_name: string;
  last_name: string;
  user_email: string;
  country: string;
  city: string;
  address: string;
  zip_code: string;
  phone_number: string;
  product_details: {
    name: string;
    price: string;
    quantity: string;
  }[];
  amount_paid: number;
  shipping_fee: number;
  created_at?: string;
  order_id: number;
};

export type CampaignDetailsType = {
  id: number;
  created_at: string;
  banner_title: string;
  banner_subtext: string;
  campaign_title: string;
  campaign_subtext: string;
  banner_image: string[];
  campaign_video: string[];
};

export type ConversionRateType = {
  USD: string;
  AED: string;
  AFN: string;
  ALL: string;
  AMD: string;
  ANG: string;
  AOA: string;
  ARS: string;
  AUD: string;
  AWG: string;
  AZN: string;
  BAM: string;
  BBD: string;
  BDT: string;
  BGN: string;
  BHD: string;
  BIF: string;
  BMD: string;
  BND: string;
  BOB: string;
  BRL: string;
  BSD: string;
  BTN: string;
  BWP: string;
  BYN: string;
  BZD: string;
  CAD: string;
  CDF: string;
  CHF: string;
  CLP: string;
  CNY: string;
  COP: string;
  CRC: string;
  CUP: string;
  CVE: string;
  CZK: string;
  DJF: string;
  DKK: string;
  DOP: string;
  DZD: string;
  EGP: string;
  ERN: string;
  ETB: string;
  EUR: string;
  FJD: string;
  FKP: string;
  FOK: string;
  GBP: string;
  GEL: string;
  GGP: string;
  GHS: string;
  GIP: string;
  GMD: string;
  GNF: string;
  GTQ: string;
  GYD: string;
  HKD: string;
  HNL: string;
  HRK: string;
  HTG: string;
  HUF: string;
  IDR: string;
  ILS: string;
  IMP: string;
  INR: string;
  IQD: string;
  IRR: string;
  ISK: string;
  JEP: string;
  JMD: string;
  JOD: string;
  JPY: string;
  KES: string;
  KGS: string;
  KHR: string;
  KID: string;
  KMF: string;
  KRW: string;
  KWD: string;
  KYD: string;
  KZT: string;
  LAK: string;
  LBP: string;
  LKR: string;
  LRD: string;
  LSL: string;
  LYD: string;
  MAD: string;
  MDL: string;
  MGA: string;
  MKD: string;
  MMK: string;
  MNT: string;
  MOP: string;
  MRU: string;
  MUR: string;
  MVR: string;
  MWK: string;
  MXN: string;
  MYR: string;
  MZN: string;
  NAD: string;
  NGN: string;
  NIO: string;
  NOK: string;
  NPR: string;
  NZD: string;
  OMR: string;
  PAB: string;
  PEN: string;
  PGK: string;
  PHP: string;
  PKR: string;
  PLN: string;
  PYG: string;
  QAR: string;
  RON: string;
  RSD: string;
  RUB: string;
  RWF: string;
  SAR: string;
  SBD: string;
  SCR: string;
  SDG: string;
  SEK: string;
  SGD: string;
  SHP: string;
  SLE: string;
  SLL: string;
  SOS: string;
  SRD: string;
  SSP: string;
  STN: string;
  SYP: string;
  SZL: string;
  THB: string;
  TJS: string;
  TMT: string;
  TND: string;
  TOP: string;
  TRY: string;
  TTD: string;
  TVD: string;
  TWD: string;
  TZS: string;
  UAH: string;
  UGX: string;
  UYU: string;
  UZS: string;
  VES: string;
  VND: string;
  VUV: string;
  WST: string;
  XCD: string;
  XDR: string;
  XOF: string;
  XPF: string;
  YER: string;
  ZAR: string;
  ZMW: string;
  ZWL: string;
};
